Rails/question_bank/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  root 'homepage#index'

  get 'homepage/index'
  get 'homepage/about', to: 'homepage#about'

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "users#edit", as: :edit_password
  patch "password", to: "users#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"
  
  resources :twitter_accounts
  resources :tweets

  namespace :api do
    namespace :v1 do
      resources :twitter_accounts
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Rails/question_bank/app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hours.from_now
  end

  after_save_commit do
    if publish_at_previously_changed?
      TweetJob.set(wait_until: publish_at).perform_later(self)
    end
  end

  def published?
    tweet_id?
  end

  def publish_to_twitter!
    tweet = twitter_account.client.update(body)
    update(tweet_id: tweet.id)
  end
end

Rails/question_bank/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Current.user.tweets.new(tweet_params)
    if @tweet.save
     # TweetJob.set(wait_until: @tweet.publish_at).perform_later(@tweet)
      redirect_to tweets_path, notice: "Tweet was scheduled successfully"
    else
      render :new
    end
  end
 
  def edit
  end

  def update
    if @tweet.update(tweet_params)
   #   TweetJob.set(wait_until: @tweet.publish_at).perform_later(@tweet)
      redirect_to tweets_path, notice: "Tweet was updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @tweet.destroy
    redirect_to tweets_path, notice: "Tweet was unscheduled"
  end

  private

  def tweet_params
    params.require(:tweet).permit(:twitter_account_id, :body, :publish_at)
  end

  def set_tweet
    @tweet = Current.user.tweets.find(params[:id])
  end
end

Rails/question_bank/app/views/tweets/_form.html.erb
<%= form_with model: tweet do |form| %>
<%= render "shared/form_errors", form: form %>
<div class="mb-3">
  <%= form.label :twitter_account_id %>
  <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, { class: "form-control" } %>
</div>

<div class="mb-3">
  <%= form.label :body %>
  <%= form.text_area :body, class: "form-control" %>
</div>

<div class="mb-3">
  <%= form.label :publish_at %>
  <div class="form-control">
    <%= form.datetime_select :publish_at %>
  </div>
</div>

<%= form.button "Schedule", class: "btn btn-primary" %>

<% end %>
<%= form_with model: @tweet do |form| %>
<% if form.object.persisted? %>
<%= button_to "Delete", form.object, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
<%end%>
<%end%>

Rails/question_bank/app/views/tweets/_tweets.html.erb
<div class="mb-3 card card-body">
  <%= tweet.body %>
  <div class="me-4">
    <%= image_tag tweet.twitter_account.image, class: "rounded-circle" if  tweet.twitter_account.image %>
    <%= link_to "@#{tweet.twitter_account.username}", "https://twitter.com/#{tweet.twitter_account.username}", target: :_blank %>
    <% if tweet.published? %>
      <%= link_to "View Tweet", "https://twitter.com/#{tweet.twitter_account.username}/status/#{tweet.tweet_id}", target: :_blank %>
    <% else %>
      Scheduled for <%= l tweet.publish_at, format: :long %>
      <%= link_to "Edit Tweet", edit_tweet_path(tweet) %>
    <% end %>
  </div>
</div>

Rails/question_bank/app/views/tweets/edit.html.erb
<h1>Edit Scheduled Tweet</h1>

<%= render "form", tweet: @tweet %>

Rails/question_bank/app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Tweets</h1>

  <% if Current.user.twitter_accounts.any? %>
    <%= link_to "Schedule a Tweet", new_tweet_path, class: "btn btn-primary" %>
  <% end %>
</div>

<% if Current.user.twitter_accounts.none? %>
  <%= link_to "Connect your Twitter Account", "/auth/twitter", class: "btn btn-primary" %>
<% end %>
<% @tweets.each do |tweet| %>
<%= render "tweets", tweet: tweet %>
<% end %>

Rails/question_bank/app/views/tweets/new.html.erb
<h1>Schedule A Tweet</h1>

<%= render "form", tweet: @tweet %>