Rails/airport/config/routes.rb
Rails.application.routes.draw do

  resources :cities
  devise_for :employees
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'flights#index'
  get 'aircraft/index'
  get 'flights/index'
  get 'flights/new'
  get 'flights/create'
  get 'flights/edit'
  get 'flights/update'
  get 'flights/destroy'
  get 'employees/index'
  get 'employees/new'
  get 'employees/create'
  get 'employees/show'
  get 'employees/edit'
  get 'employees/update'
  get 'employees/destroy'

  get 'aircraft/show'
  get 'aircraft/practice'
  get 'aircraft/index'
  get 'aircraft/new'
  get 'delete/:id', to: "aircraft#delete"
  get 'aircraft/destroy'

  resources :aircraft, :employees, :flights
  resources :flight do
    resources :flights_aircrafts
  end
  resources :schedules
  resources :certifieds
end

Rails/airport/app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :flight
  belongs_to :aircraft
  belongs_to :employee
  validates :aircraft_id, presence: true
  validates :employee_id, presence: true
  validates :flight_id, presence: true
  validate :pilot_aircraft_certified?

  
  private
  def pilot_aircraft_certified?
    aircraft = Aircraft.find(aircraft_id)
    employee = Employee.find(employee_id)
    if (employee.certified_ids && aircraft.certified_ids)
      true
    else
      false
    end
  end



end

Rails/airport/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_employee!
  before_action :require_admin_access!, except: [:index]

  def index
    if current_employee.account_type == "PILOT"
      @schedules = Schedule.includes(:employee, :flight, :aircraft).where(employee_id: current_employee.id)
    elsif current_employee.account_type == "ADMIN"
      @schedules = Schedule.includes(:employee, :flight, :aircraft)
    else
      redirect_to root_path, notice: "You must be Either admin or Pilot  to do that."
    end
  end

  def new
    @schedule = Schedule.new
    @flights = Flight.all
  end

  def create
    @flight = Flight.find(schedule_params[:flight])
    @pilot = Employee.find(schedule_params[:pilot])
    @aircraft = Aircraft.find(schedule_params[:aircraft])
    @schedule = Schedule.new()
    if helpers.create_schedule?
      redirect_to(schedules_path)
    else
      redirect_to( new_schedule_path)
    end
  end

  def edit

  end

  def update

  end

  def destroy
    @schedule = Schedule.find(params[:id])
    helpers.destroy_schedule
    redirect_to(schedules_path)
  end

  private
  def schedule_params
    params.require(:schedule).permit(:from, :destination, :flight, :aircraft, :pilot)    
  end
end

Rails/airport/app/helpers/schedule_helper.rb
module ScheduleHelper

  def create_schedule?
     if (@aircraft.availability+1.hour <= @flight.departs && 
       @pilot.availability+1.hour <= @flight.departs &&
       @aircraft.place == @flight.from &&
       @aircraft.cruising_range >= @flight.distance && 
       @pilot.place == @flight.from &&
       DateTime.now+4.hour >= @flight.departs &&
       @flight.status == 'NotScheduled' ) 
         @schedule.update(flight_id: @flight.id, aircraft_id: @aircraft.id, employee_id: @pilot.id, status: 'Scheduled')
         if @schedule.save 
           @flight.update(status: 1)
           @pilot.update(place: @flight.destination, availability: @flight.arrives )
           @aircraft.update(place: @flight.destination, availability: @flight.arrives )
           true
         end
    else
      flash[:alert] = ['Schedule for aircraft not created'] 
 
      if @aircraft.availability+1.hour > @flight.departs || @aircraft.place != @flight.from
        flash[:alert] += ['Aircraft not availble for this flight']
      end
 
      if @pilot.availability+1.hour > @flight.departs || @pilot.place != @flight.from
        flash[:alert] += ['Pilot not available for this flight']
      end
 
      if DateTime.now+4.hour < @flight.departs
        flash[:alert] += ['Can not schedule flight more than 4 hours from now']
      end
 
      if @flight.status == 'Scheduled'
        flash[:alert] += ['This flight is already scheduled']
      end
 
      if @flight.status == 'Completed'
        flash[:alert] += ['This flight is already Completed']
      end
 
      if @flight.status == 'Cancelled'
        flash[:alert] += ['This flight is already Cancelled']
      end
 
      flash[:alert] += @schedule.errors.full_messages
      false
    end
  end

  def destroy_schedule
    flight = Flight.find(@schedule.flight_id)
    pilot = Employee.find(@schedule.employee_id)
    aircraft = Aircraft.find(@schedule.aircraft_id)
    if DateTime.now+1.hour < @schedule.flight.departs
      flight.update(status: 3)
      pilot.update(availability: DateTime.now, place: @schedule.flight.from)
      aircraft.update(availability: DateTime.now, place: @schedule.flight.from)
      @schedule.destroy
    else
      flash[:alert] = ['Schedule for this cannot be destroyed as no time left'] 
    end
  end

end

Rails/airport/app/views/schedules/index.html.erb
<h1>Scheduled Aircraft List</h1>
<table class="table table-striped">
  <tr>
    <th>Flight From</th> 
    <th>Flight Destination</th> 
    <th>Aircraft</th>
    <th>Pilot</th> 
    <th>Status</th>
  </tr>
  <% @schedules.each do |schedule| %>
  <tr>
    <td><%= schedule.flight.from %></td>
    <td><%= schedule.flight.destination %></td>
    <td><%= schedule.aircraft.name %></td>
    <td><%= schedule.employee.name %></td> 
    <td><%= schedule.status %></td> 
    <td><%=  button_to "Delete", schedule_path(schedule.id), method: :delete  %></td>
  </tr>
  <% end %>
</table>

Rails/airport/app/views/schedules/new.html.erb
<%= form_with model: @schedule do |f| %>
  <div class="mb-3">
    <h3>
      <%= f.label :flightschedule, "Schedule New Aircraft Flight Here " %>
    </h3>
  </div>
  <div class="mb-3" id="from">
    <%= f.label :from, "From : " %>
    <% cities = City.pluck(:name) %>
    <% cities.append("SELECT") %>
      <%= f.select :from, cities , :selected => "SELECT" %>
  </div>
  <div class="mb-3" id="dest" style="display:none;">
    <%= f.label :destination %>
    <%= f.select :destination, ["Select"] %>
  </div>
  <div class="mb-3" id="flightSchedule" style="display:none;">
    <h5><%= f.label :schedule, "Available Flight Schedule for this route =>" %></h5>
    <table id ="flight-schedule-table" class="table table-striped">
      <tr><td>data here</td></tr>
    </table>
    <%= f.hidden_field :flight %>
  </div>
  <div class="mb-3" id="airship" style="display:none;">
    <h5><%= f.label :aircraft, "Available Aircraft for this flights =>" %></h5>
    <%= f.select :aircraft, ["Select"] %>
    <div class="mb-3" id="airship_details" style="display:none;">
    <%= f.label :cruisingtext ,"Cruising range for this Aircraft will be : " %>
    <%= f.label :cruising , id: 'cruising' %> <br>
    <%= f.label :aircraftAvailability ,"Aircraft will be available from : " %>
    <%= f.label :availability , id: 'availability' %>
    <%= f.label :aircraftPlace ,"and available at :   " %>
    <%= f.label :place , id: 'place' %>
    </div>
  </div>
  <div class="mb-3" id="pilots" style="display:none;">
  <h5><%= f.label :pilot, "Available pilot to fly this aircraft" %></h5>
    <%= f.select :pilot, ["Select"] %>
    <div class="mb-3" id="pilot_details" style="display:none;">
      <%= f.label :pilotavailabilitytext ,"Pilot will be available from : " %>
      <%= f.label :pilotavailability , id: 'pilotavailability' %>
      <%= f.label :pilotplacetext ,"and available at :   " %>
      <%= f.label :pilotplace , id: 'pilotplace' %>
      </div>
  </div>
  <div class="mb-3" id="submitbtn" style="display:none;">
    <%= f.submit "Schedule this Flight " %>
  </div>

  <% end %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script>
      let schedule_from = document.getElementById('schedule_from');
      let dest = document.getElementById('dest');
      let len = schedule_from.length;
      let aircraft_cruising = new Array();
      let aircraft_place = new Array();
      let aircraft_availability = new Array();
      let pilot_availability = new Array();
      let pilot_place = new Array();
      


      //schedule_from.addEventListener("change", show());
      $('#schedule_from').change(function(){
        dest.style.display = "block";
        schedule_destination = document.getElementById('schedule_destination');

        schedule_destination.innerHTML = "";
        let i = 0;
        let city_from = schedule_from.options[schedule_from.selectedIndex].text;
        while(i < len ){
          let city = schedule_from.options.item(i).text;
          if (city_from != city ) {
            let option = document.createElement("option");
            option.value = option.text = city ;
            schedule_destination.appendChild(option);
          }
          i++;
        }
        schedule_destination.value = "SELECT";
      });


      let count = 0;
      schedule_destination = document.getElementById('schedule_destination');
      flightSchedule = document.getElementById('flightSchedule');

  

      $('#schedule_destination').change(function(){
        flightSchedule.style.display = "block";
        let city_from = schedule_from.options[schedule_from.selectedIndex].text;
        let city_destination = schedule_destination.options[schedule_destination.selectedIndex].text;
        let data = '<tr ><td>Departs At: </td><td>Arrives At: </td><td>Distance: </td></tr>';
        
        <% Flight.where("departs >= ? " , DateTime.now).each do |flight| %>
        console.log(city_from,city_destination,"<%= flight.from %>, <%= flight.destination %>, <%= flight %>");
        if (city_from == '<%= flight.from %>' && city_destination == '<%= flight.destination %>') {
          data += "<tr class='clickable-row' id = <%= flight.id %> ><td><%= flight.departs.strftime('%a\'%d,%b,%y %I:%M %p') if flight.departs %></td><td><%= flight.arrives.strftime('%a\'%d,%b,%y %I:%M %p') if flight.arrives %></td><td><%= flight.distance %></td></tr>";
        }
        <% end %>
        $('#flight-schedule-table').html(data);
        $('#flight-schedule-table tr').click(function(){
          //alert( "Handler for .dblclick() called." );
          //document.getElementById('airship').style.display = "block";
          $(this).css('background-color','yellow').siblings().css('background-color','white');
          $('#schedule_flight').val(this.id);
          $('#airship').show();
          schedule_aircraft = document.getElementById('schedule_aircraft');
          
          schedule_aircraft.innerHTML = "";
          <%Aircraft.all.each do |aircraft|%>
             option = document.createElement("option");
             option.value = '<%= aircraft.id %>';
             option.text = '<%= aircraft.name %>';
             schedule_aircraft.appendChild(option);
             aircraft_cruising[option.value] = '<%= aircraft.cruising_range %>';
             aircraft_place[option.value] = '<%= aircraft.place %>';
             aircraft_availability[option.value] = "<%= aircraft.availability.strftime('%a\'%d,%b,%y %I:%M %p') %>";
          <% end %>
          option = document.createElement("option");
          option.value = option.text = 'SELECT';
          schedule_aircraft.appendChild(option);
          schedule_aircraft.value = "SELECT";
      });
        
      });

      $('#schedule_aircraft').change(function(){
        console.log("Aircraft selected");
        $('#pilots').show();
        $('#submitbtn').show();
        $('#airship_details').show();
        
        schedule_pilot = document.getElementById('schedule_pilot');
        $('#cruising').html(aircraft_cruising[$("#schedule_aircraft option:selected").val()]);
        $('#availability').html(aircraft_availability[$("#schedule_aircraft option:selected").val()]);
        $('#place').html(aircraft_place[$("#schedule_aircraft option:selected").val()]);
        
        schedule_pilot.innerHTML = "";
          <%Employee.where(id: Certified.pluck("employee_id").uniq()).each do |employee|%>
             option = document.createElement("option");
             option.value = '<%= employee.id %>';
             option.text = '<%= employee.name %>';
             schedule_pilot.appendChild(option);
             pilot_place[option.value] = '<%= employee.place %>';
             pilot_availability[option.value] = "<%= employee.availability.strftime('%a\'%d,%b,%y %I:%M %p') %>";
          <% end %>
          option = document.createElement("option");
          option.value = option.text = 'SELECT';
          schedule_pilot.appendChild(option);
          schedule_pilot.value = "SELECT";
      });

      $('#schedule_pilot').change(function(){
        $('#pilot_details').show();
        $('#pilotavailability').html(pilot_availability[$("#schedule_pilot option:selected").val()]);
        $('#pilotplace').html(pilot_place[$("#schedule_pilot option:selected").val()]);
      });
    </script>