Rails/avatar/config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  get 'users/signup'
  post 'users/create'
  resources :users do 
    collection do
      get 'sorting'
    end 
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Rails/avatar/app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  validates_processing_of :avatar
  validate :image_size_validation
 
  private
    def image_size_validation
      errors[:avatar] << "should be less than 500KB" if avatar.size > 5.megabytes
    end
end

Rails/avatar/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order("id")
  end

  def signup
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Successfully Create Account"
    else
      flash[:alert] = "Details Entered Incorrectly"
      render :signup
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update user_params
    if @user.save
      redirect_to root_path, notice: "Updated User"
    else
      flash[:alert] = "Details Entered Incorrectly"
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "Deleted User"
  end

  def sorting
    previous_sort_by = params[:previous_sort_by]
    sort_by = params[:sort_by]
    sort_type = params[:sort_type]

    if previous_sort_by == sort_by
      if sort_type == 'asc'
        sort_type = 'desc'
        params[:sort_type] = 'desc'
      else
        sort_type = 'asc'
        params[:sort_type] = 'asc'
      end
    end
    @users = User.all.order(sort_by+" "+sort_type)
  end

  private
  def user_params
    params.require(:user).permit(:name, :avatar, :address, :gender)
  end
end

Rails/avatar/app/helpers/index_helper.rb
module IndexHelper
end

Rails/avatar/app/views/users/_indextable.html.erb
<tr>
  <th>Avatar</th>
  <% previous_sort_by = params[:sort_by] ? params[:sort_by] : 'id'  %>
  <% sort_type = params[:sort_type] ? params[:sort_type] : 'asc' %>

  <th><%= link_to "Name", sorting_users_path(:sort_by => 'name', :previous_sort_by => previous_sort_by, :sort_type => sort_type ) , remote: true %></th>

  <th><%= link_to "Gender", sorting_users_path(:sort_by => 'gender', :previous_sort_by => previous_sort_by, :sort_type => sort_type) , remote: true %></th>

  <th><%= link_to "Address", sorting_users_path(:sort_by => 'address', :previous_sort_by => previous_sort_by, :sort_type => sort_type) , remote: true %></th>

  <th>Edit</th>
  <th>Delete</th>
</tr>

<% @users.each do |user| %>
<tr class = "rows1">
  <td><%= image_tag(user.avatar_url(:thumb).to_s) %></td>

  <td><%= user.name %></td>

  <td><%= user.gender %></td>

  <td><%= user.address %></td>

  <td><%= link_to "edit", edit_user_path(user.id)  %></td>
  <td class = "button-1"><%=  button_to "delete", user_path(user.id), method: :delete  %></td>

</tr>
<% end %>

Rails/avatar/app/views/users/edit.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, url: user_path do |form| %>
  <% if @user.errors.any? %>
  <div class="alert alert-danger">
    <% @user.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <% end %>

  <div >
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div> 
  <div >
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>
  <div >
    <%= form.label :gender %>
    <%= form.radio_button :gender, "Male" %>
    <%= form.label :gender, "Male" %>
    <%= form.radio_button :gender, "Female" %>
    <%= form.label :gender, "Female"  %>
  </div>
  <div >
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>


  <div>
    <%= form.submit "Update Data"%>
  </div>
<% end %>

Rails/avatar/app/views/users/index.html.erb
<a href = "google.com" id = "jsinfo">googel </a>
<h1>Index</h1>
<%= link_to "Sign Up", users_signup_path, id: 'elem' %>
<a href = "javascript.html" > Javascript</a>
<br>
<hr>
<b ondblclick="alert('Click!')" onmousedown="return false">
  Double-click me
</b>
<div show-info="heading">
  <h1>Users List</h1>
</div>
<br>

<!-- <button id = "test" onclick = "console.log('in the cosole using onclick event')"> Test</button> -->

<button id = "test"> Test</button>
  <div oncopy="alert('Copying forbidden!');return false">
    <table id="table1" >
      <%= render 'indextable' %>
    </table>
  </div>
    <ul id="ul"></ul>

    <button data-toggle-id="subscribe-mail">
      Show the subscription form
    </button>
    
    <form id="subscribe-mail" hidden>
      Your mail: <input type="email">
    </form>
<style>
      .selected {
      background: #0f0;
    }

    li {
      cursor: pointer;
    }
</style>
<script> 
 ul.onclick = function(event) {
      if (event.target.tagName != "LI") return;

      if (event.ctrlKey || event.metaKey) {
        toggleSelect(event.target);
      } else {
        singleSelect(event.target);
      }

    }
    ul.onmousedown = function() {
      return false;
    };

    function toggleSelect(li) {
      li.classList.toggle('selected');
    }

    function singleSelect(li) {
      let selected = ul.querySelectorAll('.selected');
      for(let elem of selected) {
        elem.classList.remove('selected');
      }
      li.classList.add('selected');
    }




  table1.insertAdjacentHTML('beforebegin', '<p>Hello</p>');
  console.log(document.body.childNodes);
  console.log(document.body.childElementCount);
  console.log(document.lastChild.nextSibling);
  let button = document.querySelector(".button-1");
  alert(button.closest('.rows1'));
  let button_del = document.getElementsByClassName("button-1");
  let allh1 = document.getElementsByTagName("h1");
  let allbutton = document.querySelectorAll(".button");
  document.getElementsByName(name);
  let table = document.getElementById('table1');
  console.log(table.id  );
  for(let i = 0; i < table.rows.length; i++){
    table.rows[i].cells[i].style.backgroundColor = 'red';
  }
  for (let elem of document.body.children) {
    if (elem.matches('a[href$="users"]')) {
      alert("The archive reference: " + elem.href );
    }
  }
  let jsinfo = document.getElementById("jsinfo");
  jsinfo.href = "google.com";
  jsinfo.className = "web" ;
  jsinfo.innerHTML = "jsinfo.com" ; 
  jsinfo.textContent = "Something" ;
  setInterval(() => elem.hidden = !elem.hidden, 1000);
  // step 1
  let newWeb = document.createElement("h2");
  // step2      create new text node
  let newText = document.createTextNode("Adding via javascript");
  // step 2 append the item or can use text.Content prperty
  newWeb.append(newText);
  // step 3 add any more attribute
  newWeb.className = 'web' ; 
  // step 4 append to the appropriate location
  let loc = document.getElementById('jsinfo');
        loc.append(newWeb);
  function getListContent() {
    let fragment = new DocumentFragment();
  
    for(let i=1; i<=3; i++) {
      let li = document.createElement('li');
      li.append(i);
      fragment.append(li);
    }
  
    return fragment;
  }
  
  ul.append(getListContent());
  function testClick(){
    console.log("test button");
    alert("you pressed test button");
  }

  //document.getElementById('test').onclick = testClick() ;
  // can add many funtion by using addEventListenenrs
  document.getElementById('test').addEventListener("click", testClick);

  let selectedTd;
  table1.onclick = function(event) {
    let td = event.target.closest('td'); // (1)
    if (!td) return; // (2)
    if (!table.contains(td)) return; // (3)
    highlight(td); // (4)
  }

  function highlight(td) {
    if (selectedTd) { // remove the existing highlight if any
      selectedTd.style.backgroundColor = 'white';
    }
    selectedTd = td;
    selectedTd.style.backgroundColor = 'yellow'; // highlight the new td
  }

  document.addEventListener('click', function(event) {
    let id = event.target.dataset.toggleId;
    if (!id) return;
    let elem = document.getElementById(id);
    elem.hidden = !elem.hidden;
  });
</script>
 

Rails/avatar/app/views/users/signup.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user,id: 'form1', url: users_create_path do |form| %>
  <% if @user.errors.any? %>
  <div class="alert alert-danger">
    <% @user.errors.full_messages.each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <% end %>

  <div >
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
    <p id = "nameMessage"></p>
  </div> 
  <div >
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>
  <div >
    <%= form.label :gender %>
    <%= form.radio_button :gender, "Male" %>
    <%= form.label :gender, "Male" %>
    <%= form.radio_button :gender, "Female" %>
    <%= form.label :gender, "Female"  %>
  </div>
  <div >
    <%= form.label :address %>
    <%= form.text_field(:address) %>
  </div>
  <div>
    <%= form.submit "Sign Up"%>
  </div>
<% end %>

<form onclick="alert('form')">FORM
  <div onclick="alert('div')">DIV
    <p onclick="alert('p')">P</p>
  </div>
</form><ul>
  <li tabindex="1">One</li>
  <li tabindex="0">Zero</li>
  <li tabindex="2">Two</li>
  <li tabindex="-1">Minus one</li>
</ul>



<style> .focused { outline: 1px solid red; } </style>



<script>
  //how to get form from the document
  console.log(document.forms.form1);
  console.log(document.forms[0]);
  console.log(document.getElementById("form1"));
  //How to interact with the specific element inside the froms
  console.log(document.forms[0].elements.user_name);
  console.log(document.forms[0].elements.user_name.value);
  //
  console.log(document.getElementsByName('user[gender]'));
  document.getElementsByName('user[gender]')[0].checked = true ;
  console.log(document.forms[0].elements.user_name);

  form.addEventListener("focusin", () => form1.classList.add('focused'));
  form.addEventListener("focusout", () => form1.classList.remove('focused'));
  function checkEntries(){
    if (!user_name.value){
      let nameMessage = document.getElementById("nameMessage");
      nameMessage.testContent = "Please ENter the name";
    }
  }

  submitData.addEventListener("click", checkEntries )
</script>

Rails/avatar/app/views/users/sorting.js.erb
document.getElementById('table1').innerHTML = ' <%= j render "indextable" %> ';