Rails/question_bank/config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  root 'homepage#index'

  get 'homepage/index'
  get 'homepage/about', to: 'homepage#about'

  get "sign_up", to: "users#new"
  post "sign_up", to: "users#create"

  delete "logout", to: "sessions#destroy"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  get "password", to: "users#edit", as: :edit_password
  patch "password", to: "users#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"
  
  resources :twitter_accounts
  resources :tweets

  namespace :api do
    namespace :v1 do
      resources :twitter_accounts
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

Rails/question_bank/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new

  end

  def create 
    @user = User.find_by_email(params[:email])

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_later
      redirect_to root_path, notice: "Sent the link to reset the password "
    else
      redirect_to root_path, notice: "Sent the link to reset the password email not present "
    end
  end

  def edit
    @user = User.find_signed(params[:token], purpose: "password_reset")
    # binding.irb to pause the code execution
  rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to sign_in_path, alert: "Password reset link has expired"
  end

  def update
    @user = User.find_signed(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Password Reset Successfully"
    else
      render :edit
    end
  end

  private
    
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

Rails/question_bank/app/views/password_resets/edit.html.erb
<h1>Reset your Password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>

<% if form.object.errors.any? %>
<div class="alert alert-danger">
  <% form.object.errors.full_messages.each do |message| %>
    <div><%= message %></div>
  <% end %>
</div>
<% end %>

<div class="mb-3">
  <%= form.label :New_Password %>
  <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
</div>
<div class="mb-3">
  <%= form.label :New_Password_confirmation %>
  <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
</div>

<div class="mb-3">
  <%= form.submit "Reset Password", class: "btn btn-primary" %>
</div>
<% end %>

Rails/question_bank/app/views/password_resets/new.html.erb
<h1>Forgot your Password</h1>

<%= form_with url: password_reset_path do |form| %>

<div class="mb-3">
  <%= form.label :email %>
  <%= form.text_field :email, class: "form-control", placeholder: "abc@gmail.com" %>
</div> 

<div class="mb-3">
  <%= form.submit "Forgot Password", class: "btn btn-primary" %>
</div>
<% end %>